export const data = [
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "What is the primary addictive substance found in tobacco?",
    correct_answer: "Nicotine",
    incorrect_answers: ["Cathinone", "Ephedrine", "Glaucine"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "Human cells typically have how many copies of each gene?",
    correct_answer: "2",
    incorrect_answers: ["1", "4", "3"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question:
      "What is the official name of the star located closest to the North Celestial Pole?",
    correct_answer: "Polaris",
    incorrect_answers: ["Eridanus", "Gamma Cephei", "Iota Cephei"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "71% of the Earth&#039;s surface is made up of",
    correct_answer: "Water",
    incorrect_answers: ["Deserts", "Continents", "Forests"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question:
      "What animal takes part in Schr&ouml;dinger&#039;s most famous thought experiment?",
    correct_answer: "Cat",
    incorrect_answers: ["Dog", "Bat", "Butterfly"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "Which of these Elements is a metalloid?",
    correct_answer: "Antimony",
    incorrect_answers: ["Tin", "Bromine", "Rubidium"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question:
      "The medical term for the belly button is which of the following?",
    correct_answer: "Umbilicus",
    incorrect_answers: ["Nevus", "Nares", "Paxillus"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "Which noble gas has the lowest atomic number?",
    correct_answer: "Helium",
    incorrect_answers: ["Neon", "Argon", "Krypton"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "What is the first element on the periodic table?",
    correct_answer: "Hydrogen",
    incorrect_answers: ["Helium", "Oxygen", "Lithium"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "The human heart has how many chambers?",
    correct_answer: "4",
    incorrect_answers: ["2", "6", "3"],
  },
];
